version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/node:16.8.0
jobs:
  build:
    working_directory: ~/my-build
    executor: docker-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run-script build
      - persist_to_workspace:
          root: ~
          paths:
            - ~/my-build
workflows:
  build_project:
    jobs:
      - build
