version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/node:16.8.0
jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build
workflows:
  build_project:
    jobs:
      - build
